### ISSUE TITLE
Making semicolon behaving like f/t?

### ISSUE THREAD

**Issue by Huxpro** [rhysd/clever-f.vim#39]
Many vimers might have got used to type `;` for repeating after `f`orward or `t`oward. So It might be reasonable to map `;` with same behaviour as well?

Any thoughts?

**Comment by rhysd** [comment]
If you use `;` for repeating previous search, I think you don't need to use this plugin. You can use original `f`/`t`. Isn't it sufficient?

**Comment by Huxpro** [comment]
@rhysd this plugin obviously provides better functionalities e.g. highlighting, searching across lines than `;`. But this plugin also disable `;`. So I was thinking mapping old habits (`;`) with better functionaliies this plugin provided might not be a bad idea

**Comment by rhysd** [comment]
Thank you for your explanation. I understand your use case. You want to use this plugin but don't want to continue to use `;` rather than repeatable `f`/`t`.
I think `<Plug>(clever-f-repeat-forward)` is available for your use case (and `<Plug>(clever-f-repeat-forward)` for moving backward if you want).

Please try:
```vim
map ; <Plug>(clever-f-repeat-forward)
```

**Comment by Huxpro** [comment]
Thx @rhysd, this works perfectly for me 👍 
Another reason for me doing this is that I also use vim in other editors (VSCode, Atom, Idea) via plugin where `clever-f` is not existing. By keeping to use `;` and `,`, I can see `clever-f` as an incremental enhancement for my native vim rather than a breaking habit change 😎 

I have post a PR for adding this tips in #40 BTW 😄
